### ISSUE TITLE
Unable to successfully run a probe in server mode

### ISSUE THREAD

**Issue by DazWilkin** [google/cloudprober#96]
It appears that the code is not successfully binding `stdin` (`stdout`, `stderr`) to `Cloudprober`.

I added some debugging and in `external.go` `sendRequest` `p.cmdStdin` is `<nil>`
```
&{redis_probe server ./redis_probe [] 0xc4200b8a50 0xc42016cf60 0xc4200acdd0 0 map[] 1 false <nil> <nil> <nil> 0xc4200aa4e0 map[] map[:1] map[] 0xc4202bea00 map[] {0 0}}
```

The only place I have found where `p.cmdStdin` is assigned is `startCmdIfNotRunning` but I added a deubgging statement to this function and it appears not to be called. Additionally `Cloudprober` reports `Creating a EXTERNAL probe: redis_probe` but `startCmdIfNotRunning` would say `Starting external command`. The former appears generated by:
https://github.com/google/cloudprober/blob/db0506435d51ab2769dbd6b16026f05ccaea8151/probes/probes.go#L155

I tried using the redis example:
```
go run main.go
2018/04/04 16:04:00 hello=world
set_latency_ms 0.629330
get_latency_ms 0.474291
```
And after building it:
```
./redis-probe
2018/04/04 16:04:18 hello=world
set_latency_ms 0.889990
get_latency_ms 0.668944
```
And, if I set the cloudprober.cfg to `mode: ONCE` it works:
```
cloudprober --config_file=./cloudprober.cfg --logtostderr --debug_log
Error while getting default lameduck lister, lameduck behavior will be disabled. Err: global lameduck service not initialized
Creating a EXTERNAL probe: redis-probe
Initialized prometheus exporter at the URL: /metrics
Running external command: ./redis-probe 
1522883241 labels=ptype=external,probe=redis-probe,dst= success=1 total=1 latency=4325.327
1522883241 labels=ptype=external,probe=redis-probe,dst= set_latency_ms=1.032 get_latency_ms=0.83
cloudprober 1522883239827938228 1522883241 labels=ptype=external,probe=redis-probe,dst= success=1 total=1 latency=4325.327
cloudprober 1522883239827938229 1522883241 labels=ptype=external,probe=redis-probe,dst= set_latency_ms=1.032 get_latency_ms=0.83
Checking validity of new label: ptype
Checking validity of new label: probe
Checking validity of new label: dst
Checking validity of new metric: success
Checking validity of new metric: total
Checking validity of new metric: latency
Checking validity of new metric: set_latency_ms
Checking validity of new metric: get_latency_ms
```
BUT:
```
cloudprober --config_file=./cloudprober.cfg --logtostderr --debug_log
Error while getting default lameduck lister, lameduck behavior will be disabled. Err: global lameduck service not initialized
Creating a EXTERNAL probe: redis-probe
Initialized prometheus exporter at the URL: /metrics
Sending a probe request 1 to the external probe server for target 
2018/04/04 16:09:19 [dazwilkin:sendRequest] &{redis-probe server ./redis-probe [] 0xc420188780 0xc420195440 0xc4200ac450 0 map[] 1 false <nil> <nil> <nil> 0xc4200aa5a0 map[] map[:1] map[] 0xc42018e980 map[] {0 0}}
2018/04/04 16:09:19 [dazwilkin:sendRequest] <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4c5077]

goroutine 47 [running]:
fmt.Fprintf(0x0, 0x0, 0xd21aa0, 0x17, 0xc42007bcd8, 0x2, 0x2, 0x82ce045d, 0xbea974a7e370a659, 0x1d)
	/usr/lib/google-golang/src/fmt/print.go:189 +0x77
github.com/google/cloudprober/probes/external/serverutils.WriteMessage(0xd99d20, 0xc420184940, 0x0, 0x0, 0x1, 0x2)
	/usr/local/google/home/dazwilkin/Projects/dazwilkin-180330-cloudprober/go/src/github.com/google/cloudprober/probes/external/serverutils/serverutils.go:96 +0x1c9
github.com/google/cloudprober/probes/external.(*Probe).sendRequest(0xc42030c000, 0xc400000001, 0xd13950, 0x0, 0xc4200b14d8, 0xc4200af770)
	/usr/local/google/home/dazwilkin/Projects/dazwilkin-180330-cloudprober/go/src/github.com/google/cloudprober/probes/external/external.go:328 +0x641
github.com/google/cloudprober/probes/external.(*Probe).runServerProbe(0xc42030c000, 0xd9bce0, 0xc420195ce0, 0xc420195980)
	/usr/local/google/home/dazwilkin/Projects/dazwilkin-180330-cloudprober/go/src/github.com/google/cloudprober/probes/external/external.go:403 +0x199
github.com/google/cloudprober/probes/external.(*Probe).runProbe(0xc42030c000, 0xd9bca0, 0xc4200ce000, 0xc420195980)
	/usr/local/google/home/dazwilkin/Projects/dazwilkin-180330-cloudprober/go/src/github.com/google/cloudprober/probes/external/external.go:462 +0x103
github.com/google/cloudprober/probes/external.(*Probe).Start(0xc42030c000, 0xd9bca0, 0xc4200ce000, 0xc420195980)
	/usr/local/google/home/dazwilkin/Projects/dazwilkin-180330-cloudprober/go/src/github.com/google/cloudprober/probes/external/external.go:478 +0x80
created by github.com/google/cloudprober.(*Prober).start
	/usr/local/google/home/dazwilkin/Projects/dazwilkin-180330-cloudprober/go/src/github.com/google/cloudprober/cloudprober.go:248 +0x2b6
```

I had originally written my own trivial probe and tried it in server mode. When this didn't work (with the same results as above), I started working from the `redis` sample.

**Background**
I'm endeavoring to deploy `Cloudprober` (successfully) and probes (unsuccessfully) to Kubernetes. The approach requires both `Cloudprober` and the probes to be containerized. In this model, it's preferable (necessary?) to have the probe run in server mode to avoid the waste of spooling up a probe container, making a singular measurement, terminating the container and then recreating another clone. IIUC this is the reasoning for the server mode probe too.

**Comment by DazWilkin** [comment]
Ah! That's it! Apologies for wasting your time. Thank you!

**Comment by manugarg** [comment]
@DazWilkin Not a problem at all :) Thanks for reporting the issue.
